# Change these first
owner: flynnd6 # Your GitHub organization or username
repo: monitoring # Your GitHub repository name

# Add your sites here
sites:
  - name: New Dimensions Active
    url: https://newdimensionsactive.ie
    maxResponseTime: 5000
  - name: CDN Prod
    url: https://cdn.newdimensionsactive.ie/wp-content/uploads/2020/03/trs_48f2dfa3dd5c5cb8fb3f5d1cc3e800c0-e1598116943298.png
    maxResponseTime: 5000
  - name: Development Website
    url: $WS_SECRET_SITE
    maxResponseTime: 5000
  - name: CDN Dev
    url: $DEV_CDN_SECRET_SITE
    maxResponseTime: 5000
  - name: NDA IP Ping
    url: 34.255.40.57
    maxResponseTime: 5000
    __dangerous__insecure: true

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StatusPage
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Update description here.
  navbar:
    - title: Status
      href: /monitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
