# Change these first
owner: flynnd6 # Your GitHub organization or username
repo: monitoring # Your GitHub repository name

# Add your sites here
sites:
  - name: New Dimensions Active
    url: https://newdimensionsactive.ie
    maxResponseTime: 5000
  - name: New Dimensions Active CDN
    url: https://cdn.newdimensionsactive.ie/wp-content/uploads/2018/11/trs-white.png
    maxResponseTime: 5000
  - name: New Dimensions Active IP
    url: 34.255.40.57
    maxResponseTime: 5000
    __dangerous__insecure: true

assignees: # Users to assign downtime issues (optional)
  - flynnd6

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: monitoring.declanflynn.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  theme: dark
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StatusPage
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitored Sites
  navbar:
    - title: Status
      href: /monitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
